# Generated by Django 3.2.6 on 2021-08-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='card',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='card_date',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
