# Generated by Django 3.2.6 on 2021-08-13 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210813_0925'),
        ('store', '0005_auto_20210813_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='territory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.territorie'),
        ),
    ]
