# Generated by Django 3.2.6 on 2021-08-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_region_territorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorie',
            name='latitute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='territorie',
            name='longitute',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
